### ISSUE TITLE
FILTER_SANITIZE_MAGIC_QUOTES is deprecated (Matomo 3.13.1)

### ISSUE THREAD

**Issue by sapkra** [Romain/Matomo-IP-to-Company#2]
WARNING: /var/www/matomo/plugins/IPtoCompany/API.php(225): Deprecated - filter_var(): FILTER_SANITIZE_MAGIC_QUOTES is deprecated, use FILTER_SANITIZE_ADD_SLASHES instead - Matomo 3.13.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: IPtoCompany, Action: getCompanies, Method: IPtoCompany.getCompanies, In CLI mode: false)

WARNING: /var/www/matomo/plugins/IPtoCompany/API.php(245): Deprecated - filter_var(): FILTER_SANITIZE_MAGIC_QUOTES is deprecated, use FILTER_SANITIZE_ADD_SLASHES instead - Matomo 3.13.1 - Please report this message in the Matomo forums: https://forum.matomo.org (please do a search first as it might have been reported already) (Module: IPtoCompany, Action: getCompanies, Method: IPtoCompany.getCompanies, In CLI mode: false)

**Comment by Romain** [comment]
Thanks @sapkra for pointing this out.
Based on my searches, it seems that this deprecation is related specifically to PHP 7.4.*: https://www.php.net/manual/en/migration74.deprecated.php.

This version of PHP has been released on 01/25/2020.
I'll try to push a fix ASAP for this, though I don't think that this is something critical or that a huge volume of users will encounter.

I'll keep you posted anyway.

**Comment by sapkra** [comment]
Ok thanks for your fast support. 
FYI: I'm using the official matomo docker image and got some large yellow warning boxes in my UI.

**Comment by Romain** [comment]
Thanks for these precisions @sapkra. I didn't that @matomo-org had Docker images, or that they were using PHP 7.4.
I understand that this can be stressful to see these boxes, but there's no fundamental issue occurring in the background.

**Comment by sapkra** [comment]
Yeah I know - these are just deprecation warnings but I would really appreciate it if you could find some time to fix them sometime in the future.

**Comment by Romain** [comment]
Hi @sapkra,

I published a new version with a fix. Could you tell me if this solves your problem?
It's version [0.2.8](https://github.com/Romain/Matomo-IP-to-Company/releases/tag/0.2.8).

**Comment by sapkra** [comment]
![image](https://user-images.githubusercontent.com/8087568/75262721-379b1f00-57ed-11ea-83ce-bd364f07fec6.png)

Thanks but for some reason I'm still getting the warnings after updating to 0.2.8.  But also just sometimes e.g. always when I'm going to the matomo settings from the home screen. After reloading the settings menu the warnings are gone.

**Comment by Romain** [comment]
Thanks for this follow-up @sapkra. This inconsistency in the behaviour is weird. What you describe to me looks like an improvement from the initial situation though.
Since it's not occurring all the time, particularly when you're on the home screen or on the Socities screen, I'm closing this issue.
Thanks for pointing it out!
